<?php
/**
 * @file
 * ECK's requirements, schemas, and logic for install and uninstall.
 */

/**
 * Implements hook_schema().
 *
 * Create the database table that will store the entities information.
 * All that we need for each entity is a name and a label.
 */
function eck_schema() {

  $schema = array();

  $cache_schema = backdrop_get_schema_unprocessed('system', 'cache');

  // Schema for an eck only cache table.
  $schema['cache_eck'] = $cache_schema;

  foreach (EckEntityType::loadAll() as $entity_type) {
    // Also support Entity Cache.
    $schema["cache_entity_{$entity_type->name}"] = $cache_schema;
    $schema["cache_entity_{$entity_type->name}"]['description'] = "Cache table used to store {$entity_type->name} entity records.";

    // The function eck__entity_type__schema returns a schema for the entity type
    // given and entity_type object.
    $schema = array_merge($schema, array("eck_{$entity_type->name}" => eck__entity_type__schema($entity_type)));
  }
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function eck_update_last_removed() {
  return 7011;
}

/**
 * Adjustments to entity type schema for ECK entities and ensuring entitycache
 * tables exist.
 */
function eck_update_1000() {
  // Get all entity types from `eck_entity_type` table and ensure that the
  // `entity_type` column exists.
  if (db_table_exists('eck_entity_type')) {
    $entity_types = db_query("SELECT name FROM {eck_entity_type}")->fetchAll();
    foreach ($entity_types as $entity_type) {
      // If the `entity_type` column does not exist, add it.
      if (!db_field_exists('eck_' . $entity_type->name, 'entity_type')) {
        db_add_field('eck_' . $entity_type->name, 'entity_type', array(
          'description' => "The entity type this bundle belongs to",
          'default' => $entity_type->name,
          'type' => 'varchar',
          'length' => 128,
          'not null' => TRUE,
        ));
      }
    }
    // Ensure that entitycache tables for ECK entities exist.
    $cache_schema = backdrop_get_schema_unprocessed('system', 'cache');
    foreach ($entity_types as $entity_type) {
      if (!db_table_exists("cache_entity_{$entity_type->name}")) {
        $schema = $cache_schema;
        $schema['description'] = "Cache table used to store {$entity_type->name} entity records.";
        db_create_table("cache_entity_{$entity_type->name}", $schema);
      }
    }
  }
  // Submodule entry is no longer needed since we've added the functionality
  // to the main module.
  db_delete('system')
    ->condition('name', 'eck_entitycache')
    ->condition('type', 'module')
    ->execute();
}

/**
 * Updates ECK entity types and bundles to CMI.
 */
function eck_update_1001() {
  $query = db_select('eck_entity_type', 'e')
        ->fields('e')
        ->orderBy('e.name', 'ASC');
  $entity_types = array();
  foreach ($query->execute() as $entity_object) {
    $entity_types[$entity_object->name] = $entity_object;
  }
  foreach ($entity_types as $entity_object) {
    $config = config('eck.entity_type.' . $entity_object->name);
    $config->set('name', $entity_object->name);
    $config->set('label', $entity_object->label);
    $config->set('properties', unserialize($entity_object->properties));
    $config->save();
  }
  db_drop_table('eck_entity_type');

  $query = db_select('eck_bundle', 'b')
        ->fields('b')
        ->orderBy('b.name', 'ASC');
  $bundles = array();
  foreach ($query->execute() as $entity_object) {
    $bundles[$entity_object->name] = $entity_object;
  }
  foreach ($bundles as $bundle_object) {
    $config = config('eck.bundle.' . $bundle_object->entity_type . '.' . $bundle_object->name);
    $config->set('name', $bundle_object->name);
    $config->set('label', $bundle_object->label);
    $config->set('entity_type', $bundle_object->entity_type);
    $config->set('settings', unserialize($bundle_object->settings));
    $config->save();
  }
  db_drop_table('eck_bundle');

}
